#!/usr/bin/env bash
###################################################################################################
# patch-trixie-gpiod.sh — libgpiod v2 compatibility helper for P2_app (Debian Trixie+)
#
# Fixes / behaviors:
#   - Correct argument parsing (running with no args is valid)
#   - Supports: --revert, --dry-run, --help
#   - Locates P2_app (or uses P2APP_DIR)
#   - On libgpiod v2+: ensures g2panel_v2.c exists (only creates if missing)
#   - Patches Makefile idempotently:
#        * link line includes $(LDLIBS)
#        * -D GIT_DATE= -> -DGIT_DATE= (cosmetic)
#        * removes -lgpiod from LIBS= if LDLIBS supplies it (avoid duplicates)
#   - Creates timestamped backups before touching Makefile
###################################################################################################

set -Eeuo pipefail

hr(){ printf '##############################################################\n'; }
log(){ printf '%s\n' "$*"; }
die(){ log "ERROR: $*"; exit 1; }

trap 'die "command failed (line $LINENO): $BASH_COMMAND"' ERR

SATURN_ROOT="${SATURN_ROOT:-$HOME/github/Saturn}"

usage() {
  cat <<'EOF'
Usage: patch-trixie-gpiod.sh [--dry-run] [--revert] [--help]

Options:
  --dry-run   Show what would change (does not modify files)
  --revert    Restore most recent Makefile backup created by this script and remove g2panel_v2.c
  --help      Show this help

Overrides (environment):
  SATURN_ROOT=/path/to/Saturn
  P2APP_DIR=/path/to/P2_app
EOF
}

DRY_RUN=0
REVERT=0

# IMPORTANT FIX: iterate over "$@" directly (no empty-arg injection)
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --revert)  REVERT=1 ;;
    --help|-h) usage; exit 0 ;;
    "") ;;  # ignore accidental empty args safely
    *) die "Unknown argument: $arg" ;;
  esac
done

# Match update-p2app.sh candidate logic for consistency
P2APP_CANDIDATES=(
  "$SATURN_ROOT/sw_projects/P2_app"
  "$SATURN_ROOT/sw_projects/P2_App"
  "$SATURN_ROOT/P2_app"
  "$SATURN_ROOT/P2_App"
  "$SATURN_ROOT/sw_projects/p2app"
  "$SATURN_ROOT/p2app"
)

detect_p2app_dir() {
  if [[ -n "${P2APP_DIR:-}" ]]; then
    [[ -d "$P2APP_DIR" ]] || die "P2APP_DIR is set but not a directory: $P2APP_DIR"
    printf '%s\n' "$P2APP_DIR"
    return 0
  fi

  local c
  for c in "${P2APP_CANDIDATES[@]}"; do
    if [[ -d "$c" ]] && { [[ -f "$c/p2app.c" ]] || [[ -f "$c/Makefile" ]] || [[ -f "$c/makefile" ]]; }; then
      printf '%s\n' "$c"
      return 0
    fi
  done

  die "P2_app directory not found under SATURN_ROOT=$SATURN_ROOT (set P2APP_DIR to override)"
}

detect_gpiod_version() {
  local ver=""

  if command -v pkg-config >/dev/null 2>&1 && pkg-config --exists libgpiod; then
    ver="$(pkg-config --modversion libgpiod 2>/dev/null || true)"
  fi

  if [[ -z "$ver" ]] && command -v gpiodetect >/dev/null 2>&1; then
    ver="$(gpiodetect -V 2>&1 | awk '{print $NF}' || true)"
  fi

  [[ -n "$ver" ]] || ver="1.0.0"
  printf '%s\n' "$ver"
}

backup_file() {
  local f="$1"
  local ts bak
  ts="$(date +%Y%m%d-%H%M%S)"
  bak="${f}.bak.gpiodv2.${ts}"

  if (( DRY_RUN )); then
    log "DRY-RUN: would create backup: $bak"
    return 0
  fi

  cp -a "$f" "$bak"
  log "Backup: $bak"
}

most_recent_backup() {
  local f="$1"
  ls -1t "${f}.bak.gpiodv2."* 2>/dev/null | head -n 1 || true
}

write_g2panel_v2_if_missing() {
  local p2dir="$1"
  local out="$p2dir/g2panel_v2.c"

  if [[ -f "$out" ]]; then
    log "g2panel_v2.c already exists; leaving as-is."
    return 0
  fi

  (( DRY_RUN )) && { log "DRY-RUN: would write $out"; return 0; }

  cat >"$out" <<'EOF'
/*
 * g2panel_v2.c - libgpiod v2 compatible front-panel GPIO access
 *
 * Generated by patch-trixie-gpiod.sh only if missing.
 *
 * You can override chip path with:
 *   export P2_GPIOD_CHIP=/dev/gpiochipX
 */

#define _GNU_SOURCE
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gpiod.h>

#ifndef P2_GPIOD_CHIP_DEFAULT
#define P2_GPIOD_CHIP_DEFAULT "/dev/gpiochip0"
#endif

static const char *chip_path(void)
{
    const char *p = getenv("P2_GPIOD_CHIP");
    if (p && *p) return p;
    return P2_GPIOD_CHIP_DEFAULT;
}

static struct gpiod_chip *open_chip(void)
{
    struct gpiod_chip *chip = gpiod_chip_open(chip_path());
    if (!chip) {
        fprintf(stderr, "g2panel_v2: gpiod_chip_open(%s) failed: %s\n",
                chip_path(), strerror(errno));
    }
    return chip;
}

/* Example output write by offset */
int g2panel_set_gpio(int offset, int value)
{
    int rc = -1;
    struct gpiod_chip *chip = open_chip();
    if (!chip) return -1;

    struct gpiod_line_settings *settings = gpiod_line_settings_new();
    struct gpiod_request_config *cfg = gpiod_request_config_new();
    struct gpiod_line_config *lcfg = gpiod_line_config_new();
    struct gpiod_line_request *req = NULL;

    if (!settings || !cfg || !lcfg) goto out;

    gpiod_line_settings_set_direction(settings, GPIOD_LINE_DIRECTION_OUTPUT);
    gpiod_line_settings_set_output_value(settings, value ? GPIOD_LINE_VALUE_ACTIVE : GPIOD_LINE_VALUE_INACTIVE);

    if (gpiod_line_config_add_line_settings(lcfg, (unsigned int[]){(unsigned int)offset}, 1, settings) < 0) {
        fprintf(stderr, "g2panel_v2: add_line_settings failed: %s\n", strerror(errno));
        goto out;
    }

    gpiod_request_config_set_consumer(cfg, "p2app");

    req = gpiod_chip_request_lines(chip, cfg, lcfg);
    if (!req) {
        fprintf(stderr, "g2panel_v2: request_lines(offset=%d) failed: %s\n", offset, strerror(errno));
        goto out;
    }

    if (gpiod_line_request_set_value(req, (unsigned int)offset,
                                     value ? GPIOD_LINE_VALUE_ACTIVE : GPIOD_LINE_VALUE_INACTIVE) < 0) {
        fprintf(stderr, "g2panel_v2: set_value(offset=%d) failed: %s\n", offset, strerror(errno));
        goto out;
    }

    rc = 0;

out:
    if (req) gpiod_line_request_release(req);
    if (settings) gpiod_line_settings_free(settings);
    if (cfg) gpiod_request_config_free(cfg);
    if (lcfg) gpiod_line_config_free(lcfg);
    if (chip) gpiod_chip_close(chip);
    return rc;
}
EOF

  log "Wrote v2-compatible implementation: $out"
}

patch_makefile() {
  local p2dir="$1"
  local mf=""

  if [[ -f "$p2dir/Makefile" ]]; then
    mf="$p2dir/Makefile"
  elif [[ -f "$p2dir/makefile" ]]; then
    mf="$p2dir/makefile"
  else
    log "No Makefile found; skipping Makefile patch."
    return 0
  fi

  backup_file "$mf"

  # 1) Ensure link line includes $(LDLIBS)
  if grep -q '\$(LDLIBS)' "$mf"; then
    log "Makefile: link rule already references \$(LDLIBS)"
  else
    if (( DRY_RUN )); then
      log "DRY-RUN: would add \$(LDLIBS) to link rule in $mf"
    else
      sed -i 's/$(LD) -o $(TARGET) $(OBJS) $(LDFLAGS) $(LIBS)/$(LD) -o $(TARGET) $(OBJS) $(LDFLAGS) $(LIBS) $(LDLIBS)/' "$mf" || true
    fi
  fi

  # 2) -D GIT_DATE= -> -DGIT_DATE=
  if (( DRY_RUN )); then
    log "DRY-RUN: would normalize -D GIT_DATE -> -DGIT_DATE in $mf"
  else
    sed -i -E 's/-D[[:space:]]+GIT_DATE=/-DGIT_DATE=/g' "$mf"
  fi

  # 3) If LDLIBS supplies gpiod, remove -lgpiod from LIBS=
  local ldl_has_gpiod=0
  if grep -Eq 'pkg-config[[:space:]]+--libs[[:space:]]+libgpiod|LDLIBS[[:space:]]*.*-lgpiod' "$mf"; then
    ldl_has_gpiod=1
  fi

  if (( ldl_has_gpiod )); then
    if (( DRY_RUN )); then
      log "DRY-RUN: would remove -lgpiod from LIBS= in $mf (LDLIBS supplies it)"
    else
      sed -i -E '/^LIBS[[:space:]]*=/ s/[[:space:]]-lgpiod([[:space:]]|$)/\1/g' "$mf"
    fi
  fi

  log "Makefile patch complete."
}

do_revert() {
  local p2dir="$1"

  if [[ -f "$p2dir/g2panel_v2.c" ]]; then
    if (( DRY_RUN )); then
      log "DRY-RUN: would remove $p2dir/g2panel_v2.c"
    else
      rm -f "$p2dir/g2panel_v2.c"
      log "Removed: $p2dir/g2panel_v2.c"
    fi
  fi

  local mf=""
  [[ -f "$p2dir/Makefile" ]] && mf="$p2dir/Makefile"
  [[ -z "$mf" && -f "$p2dir/makefile" ]] && mf="$p2dir/makefile"

  if [[ -z "$mf" ]]; then
    log "No Makefile found; nothing to restore."
    return 0
  fi

  local bak
  bak="$(most_recent_backup "$mf")"
  if [[ -z "$bak" ]]; then
    log "No backups found for $mf (pattern: ${mf}.bak.gpiodv2.*). Nothing to revert."
    return 0
  fi

  if (( DRY_RUN )); then
    log "DRY-RUN: would restore $mf from $bak"
  else
    cp -a "$bak" "$mf"
    log "Restored: $mf from $bak"
  fi
}

# ---------------- main ----------------
P2DIR="$(detect_p2app_dir)"
GPIOD_VER="$(detect_gpiod_version)"
GPIOD_MAJOR="${GPIOD_VER%%.*}"

log "Detected libgpiod version: $GPIOD_VER"

if (( REVERT )); then
  hr; log "REVERT requested"; hr
  do_revert "$P2DIR"
  log "Revert complete."
  exit 0
fi

if (( GPIOD_MAJOR < 2 )); then
  log "libgpiod is v${GPIOD_MAJOR} (v1) — no v2 patch needed."
  exit 0
fi

log "libgpiod is v2+; ensuring v2-compatible implementation: g2panel_v2.c"
write_g2panel_v2_if_missing "$P2DIR"

patch_makefile "$P2DIR"

log "All set. Build with: make -C \"$P2DIR\" clean && make"
